'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
'
Namespace net.nbnws.www
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="NBNTaxonomySoapBinding", [Namespace]:="http://webservices.searchnbn.net/taxonomyService"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Taxon()))>  _
    Partial Public Class GatewayWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetTaxonomySearchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.G21.My.MySettings.Default.DictaRecord_net_nbnws_www_GatewayWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetTaxonomySearchCompleted As GetTaxonomySearchCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.searchnbn.net/taxonomyService/GetTaxonomySearch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetTaxonomySearch(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://webservices.searchnbn.net/taxonomyQuery")> ByVal TaxonomySearchRequest As TaxonomySearchRequest) As <System.Xml.Serialization.XmlArrayAttribute("TaxonomySearchList", [Namespace]:="http://webservices.searchnbn.net/taxonomyData"), System.Xml.Serialization.XmlArrayItemAttribute("Taxon", IsNullable:=false)> Taxon()
            Dim results() As Object = Me.Invoke("GetTaxonomySearch", New Object() {TaxonomySearchRequest})
            Return CType(results(0),Taxon())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTaxonomySearchAsync(ByVal TaxonomySearchRequest As TaxonomySearchRequest)
            Me.GetTaxonomySearchAsync(TaxonomySearchRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTaxonomySearchAsync(ByVal TaxonomySearchRequest As TaxonomySearchRequest, ByVal userState As Object)
            If (Me.GetTaxonomySearchOperationCompleted Is Nothing) Then
                Me.GetTaxonomySearchOperationCompleted = AddressOf Me.OnGetTaxonomySearchOperationCompleted
            End If
            Me.InvokeAsync("GetTaxonomySearch", New Object() {TaxonomySearchRequest}, Me.GetTaxonomySearchOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTaxonomySearchOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTaxonomySearchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTaxonomySearchCompleted(Me, New GetTaxonomySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.searchnbn.net/taxonomyQuery")>  _
    Partial Public Class TaxonomySearchRequest
        
        Private itemField As Object
        
        Private itemElementNameField As ItemChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SpeciesName", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("TaxonVersionKey", GetType(Object)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.searchnbn.net/taxonomyData")>  _
    Partial Public Class Taxon
        
        Private taxonNameField As TaxonName
        
        Private authorityField As String
        
        Private taxonReportingCategoryField As String
        
        Private aggregateListField() As Taxon
        
        Private lowerTaxaListField() As Taxon
        
        Private synonymListField() As Taxon
        
        Private taxonVersionKeyField As String
        
        '''<remarks/>
        Public Property TaxonName() As TaxonName
            Get
                Return Me.taxonNameField
            End Get
            Set
                Me.taxonNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxonReportingCategory() As String
            Get
                Return Me.taxonReportingCategoryField
            End Get
            Set
                Me.taxonReportingCategoryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Taxon", IsNullable:=false)>  _
        Public Property AggregateList() As Taxon()
            Get
                Return Me.aggregateListField
            End Get
            Set
                Me.aggregateListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Taxon", IsNullable:=false)>  _
        Public Property LowerTaxaList() As Taxon()
            Get
                Return Me.lowerTaxaListField
            End Get
            Set
                Me.lowerTaxaListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Taxon", IsNullable:=false)>  _
        Public Property SynonymList() As Taxon()
            Get
                Return Me.synonymListField
            End Get
            Set
                Me.synonymListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property taxonVersionKey() As String
            Get
                Return Me.taxonVersionKeyField
            End Get
            Set
                Me.taxonVersionKeyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.searchnbn.net/taxonomyData")>  _
    Partial Public Class TaxonName
        
        Private wellFormedField As Boolean
        
        Private isScientificField As Boolean
        
        Private isPreferredNameField As Boolean
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property wellFormed() As Boolean
            Get
                Return Me.wellFormedField
            End Get
            Set
                Me.wellFormedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property isScientific() As Boolean
            Get
                Return Me.isScientificField
            End Get
            Set
                Me.isScientificField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property isPreferredName() As Boolean
            Get
                Return Me.isPreferredNameField
            End Get
            Set
                Me.isPreferredNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.searchnbn.net/taxonomyQuery", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        SpeciesName
        
        '''<remarks/>
        TaxonVersionKey
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub GetTaxonomySearchCompletedEventHandler(ByVal sender As Object, ByVal e As GetTaxonomySearchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTaxonomySearchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Taxon()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Taxon())
            End Get
        End Property
    End Class
End Namespace
